dataset_name: stanfordnlp/imdb
model_name: distilbert-base-uncased

raw_data_dir: data/raw/imdb
processed_data_dir: data/processed/imdb_tokenized
output_dir: models/distilbert-imdb

max_length: 128
batch_size: 16
num_epochs: 1
lr: 2e-5
seed: 42
logging_level: "INFO"

max_train_samples: 2000
max_eval_samples: 1000

freeze_base: true
